DROP DATABASE IF EXISTS db_tb100;
CREATE DATABASE db_tb100;
USE db_tb100;
DROP PROCEDURE IF EXISTS lr_time2;
delimiter $$
CREATE PROCEDURE lr_time2()
BEGIN
    CREATE TABLE tb_base(
    `any_date` date,
    `any_time` time,
    `any_datetime` datetime
    );
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());    
    INSERT INTO tb_base VALUES (curdate(),curtime(),now());
    
    CREATE TABLE tb_test1 SELECT * FROM tb_base WHERE 1=2;
    CREATE TABLE tb_test2 SELECT * FROM tb_base;
    CREATE TABLE tb_test3 LIKE tb_base;
    CREATE TABLE tb_test4 SELECT * FROM tb_base;
    CREATE TABLE tb_test5 SELECT * FROM tb_base;
    CREATE TABLE tb_test6 SELECT * FROM tb_base;
    CREATE TABLE tb_test7 SELECT * FROM tb_base;
    CREATE TABLE tb_test8 SELECT * FROM tb_base;
    CREATE TABLE tb_test9 SELECT * FROM tb_base;
    CREATE TABLE tb_test10 SELECT * FROM tb_base;
    CREATE TABLE tb_test11 SELECT * FROM tb_base;
    CREATE TABLE tb_test12 SELECT * FROM tb_base;
    CREATE TABLE tb_test13 SELECT * FROM tb_base;
    CREATE TABLE tb_test14 SELECT * FROM tb_base;
    CREATE TABLE tb_test15 SELECT * FROM tb_base;
    CREATE TABLE tb_test16 SELECT * FROM tb_base;
    CREATE TABLE tb_test17 SELECT * FROM tb_base;
    CREATE TABLE tb_test18 SELECT * FROM tb_base;
    CREATE TABLE tb_test19 SELECT * FROM tb_base;
    CREATE TABLE tb_test20 SELECT * FROM tb_base;
    CREATE TABLE tb_test21 SELECT * FROM tb_base;
    CREATE TABLE tb_test22 SELECT * FROM tb_base;
    CREATE TABLE tb_test23 SELECT * FROM tb_base;
    CREATE TABLE tb_test24 SELECT * FROM tb_base;
    CREATE TABLE tb_test25 SELECT * FROM tb_base;
    CREATE TABLE tb_test26 SELECT * FROM tb_base;
    CREATE TABLE tb_test27 SELECT * FROM tb_base;
    CREATE TABLE tb_test28 SELECT * FROM tb_base;
    CREATE TABLE tb_test29 SELECT * FROM tb_base;
    CREATE TABLE tb_test30 SELECT * FROM tb_base;
    CREATE TABLE tb_test31 SELECT * FROM tb_base;
    CREATE TABLE tb_test32 SELECT * FROM tb_base;
    CREATE TABLE tb_test33 SELECT * FROM tb_base;
    CREATE TABLE tb_test34 SELECT * FROM tb_base;
    CREATE TABLE tb_test35 SELECT * FROM tb_base;
    CREATE TABLE tb_test36 SELECT * FROM tb_base;
    CREATE TABLE tb_test37 SELECT * FROM tb_base;
    CREATE TABLE tb_test38 SELECT * FROM tb_base;
    CREATE TABLE tb_test39 SELECT * FROM tb_base;
    CREATE TABLE tb_test40 SELECT * FROM tb_base;
    CREATE TABLE tb_test41 SELECT * FROM tb_base;
    CREATE TABLE tb_test42 SELECT * FROM tb_base;
    CREATE TABLE tb_test43 SELECT * FROM tb_base;
    CREATE TABLE tb_test44 SELECT * FROM tb_base;
    CREATE TABLE tb_test45 SELECT * FROM tb_base;
    CREATE TABLE tb_test46 SELECT * FROM tb_base;
    CREATE TABLE tb_test47 SELECT * FROM tb_base;
    CREATE TABLE tb_test48 SELECT * FROM tb_base;
    CREATE TABLE tb_test49 SELECT * FROM tb_base;
    CREATE TABLE tb_test50 SELECT * FROM tb_base;
    CREATE TABLE tb_test51 SELECT * FROM tb_base;
    CREATE TABLE tb_test52 SELECT * FROM tb_base;
    CREATE TABLE tb_test53 SELECT * FROM tb_base;
    CREATE TABLE tb_test54 SELECT * FROM tb_base;
    CREATE TABLE tb_test55 SELECT * FROM tb_base;
    CREATE TABLE tb_test56 SELECT * FROM tb_base;
    CREATE TABLE tb_test57 SELECT * FROM tb_base;
    CREATE TABLE tb_test58 SELECT * FROM tb_base;
    CREATE TABLE tb_test59 SELECT * FROM tb_base;
    CREATE TABLE tb_test60 SELECT * FROM tb_base;
    CREATE TABLE tb_test61 SELECT * FROM tb_base;
    CREATE TABLE tb_test62 SELECT * FROM tb_base;
    CREATE TABLE tb_test63 SELECT * FROM tb_base;
    CREATE TABLE tb_test64 SELECT * FROM tb_base;
    CREATE TABLE tb_test65 SELECT * FROM tb_base;
    CREATE TABLE tb_test66 SELECT * FROM tb_base;
    CREATE TABLE tb_test67 SELECT * FROM tb_base;
    CREATE TABLE tb_test68 SELECT * FROM tb_base;
    CREATE TABLE tb_test69 SELECT * FROM tb_base;
    CREATE TABLE tb_test70 SELECT * FROM tb_base;
    CREATE TABLE tb_test71 SELECT * FROM tb_base;
    CREATE TABLE tb_test72 SELECT * FROM tb_base;
    CREATE TABLE tb_test73 SELECT * FROM tb_base;
    CREATE TABLE tb_test74 SELECT * FROM tb_base;
    CREATE TABLE tb_test75 SELECT * FROM tb_base;
    CREATE TABLE tb_test76 SELECT * FROM tb_base;
    CREATE TABLE tb_test77 SELECT * FROM tb_base;
    CREATE TABLE tb_test78 SELECT * FROM tb_base;
    CREATE TABLE tb_test79 SELECT * FROM tb_base;
    CREATE TABLE tb_test80 SELECT * FROM tb_base;
    CREATE TABLE tb_test81 SELECT * FROM tb_base;
    CREATE TABLE tb_test82 SELECT * FROM tb_base;
    CREATE TABLE tb_test83 SELECT * FROM tb_base;
    CREATE TABLE tb_test84 SELECT * FROM tb_base;
    CREATE TABLE tb_test85 SELECT * FROM tb_base;
    CREATE TABLE tb_test86 SELECT * FROM tb_base;
    CREATE TABLE tb_test87 SELECT * FROM tb_base;
    CREATE TABLE tb_test88 SELECT * FROM tb_base;
    CREATE TABLE tb_test89 SELECT * FROM tb_base;
    CREATE TABLE tb_test90 SELECT * FROM tb_base;
    CREATE TABLE tb_test91 SELECT * FROM tb_base;
    CREATE TABLE tb_test92 SELECT * FROM tb_base;
    CREATE TABLE tb_test93 SELECT * FROM tb_base;
    CREATE TABLE tb_test94 SELECT * FROM tb_base;
    CREATE TABLE tb_test95 SELECT * FROM tb_base;
    CREATE TABLE tb_test96 SELECT * FROM tb_base;
    CREATE TABLE tb_test97 SELECT * FROM tb_base;
    CREATE TABLE tb_test98 SELECT * FROM tb_base;
    CREATE TABLE tb_test99 SELECT * FROM tb_base;
    CREATE TABLE tb_test100 SELECT * FROM tb_base;
    
END
$$

delimiter ;
call lr_time2();
